export const exploreCategories = [
  { id: "fresh", name: "Fresh Fruits\n& Vegetable", tint: "#EEF8F1", border: "#A8D8B6" },
  { id: "oil", name: "Cooking Oil\n& Ghee", tint: "#FFF7F0", border: "#F3C899" },
  { id: "meat", name: "Meat & Fish", tint: "#FDEEEE", border: "#E9B4AF" },
  { id: "bakery", name: "Bakery & Snacks", tint: "#F6EFFA", border: "#D6B9EA" },
  { id: "dairy", name: "Dairy & Eggs", tint: "#FFF9E8", border: "#E7D38C" },
  { id: "beverages", name: "Beverages", tint: "#EDF6FF", border: "#B8D8F4" },
];

export const filterCategories = [
  { id: "eggs", label: "Eggs" },
  { id: "noodles", label: "Noodles & Pasta" },
  { id: "chips", label: "Chips & Crisps" },
  { id: "fast-food", label: "Fast Food" },
];

export const filterBrands = [
  { id: "individual-collection", label: "Individual Collection" },
  { id: "cocola", label: "Cocola" },
  { id: "ifad", label: "Ifad" },
  { id: "kazi-farmas", label: "Kazi Farmas" },
];

export const products = [
  {
    id: "banana",
    name: "Organic Bananas",
    subtitle: "7pcs, Price",
    price: 4.99,
    image: require("./assets/banana.png"),
    section: "featured",
    category: "fresh",
    filterCategory: "fast-food",
    brand: "individual-collection",
  },
  {
    id: "apple",
    name: "Red Apple",
    subtitle: "1kg, Price",
    price: 4.99,
    image: require("./assets/apple.png"),
    section: "featured",
    category: "fresh",
    filterCategory: "fast-food",
    brand: "individual-collection",
  },
  {
    id: "pepper",
    name: "Bell Pepper Red",
    subtitle: "1kg, Price",
    price: 4.99,
    image: require("./assets/ot.png"),
    section: "bestSelling",
    category: "fresh",
    filterCategory: "fast-food",
    brand: "individual-collection",
  },
  {
    id: "ginger",
    name: "Ginger",
    subtitle: "250gm, Price",
    price: 2.99,
    image: require("./assets/gung.png"),
    section: "bestSelling",
    category: "fresh",
    filterCategory: "fast-food",
    brand: "individual-collection",
  },
  {
    id: "beef",
    name: "Beef Bone",
    subtitle: "1kg, Price",
    price: 4.99,
    image: require("./assets/beefbone.png"),
    section: "groceries",
    category: "meat",
    filterCategory: "fast-food",
    brand: "individual-collection",
  },
  {
    id: "chicken",
    name: "Broiler Chicken",
    subtitle: "1kg, Price",
    price: 4.99,
    image: require("./assets/chicken.png"),
    section: "groceries",
    category: "meat",
    filterCategory: "fast-food",
    brand: "kazi-farmas",
  },
  {
    id: "diet-coke",
    name: "Diet Coke",
    subtitle: "355ml, Price",
    price: 1.99,
    image: require("./assets/coke.png"),
    section: "beverages",
    category: "beverages",
    filterCategory: "chips",
    brand: "cocola",
  },
  {
    id: "sprite",
    name: "Sprite Can",
    subtitle: "325ml, Price",
    price: 1.5,
    image: require("./assets/sprite.png"),
    section: "beverages",
    category: "beverages",
    filterCategory: "chips",
    brand: "cocola",
  },
  {
    id: "apple-grape",
    name: "Apple & Grape Juice",
    subtitle: "2L, Price",
    price: 15.5,
    image: require("./assets/apple-juice.png"),
    section: "beverages",
    category: "beverages",
    filterCategory: "chips",
    brand: "ifad",
  },
  {
    id: "orange",
    name: "Orange Juice",
    subtitle: "2L, Price",
    price: 15.99,
    image: require("./assets/orange-juice.png"),
    section: "beverages",
    category: "beverages",
    filterCategory: "chips",
    brand: "ifad",
  },
  {
    id: "coca",
    name: "Coca Cola Can",
    subtitle: "325ml, Price",
    price: 4.99,
    image: require("./assets/cocacola.png"),
    section: "beverages",
    category: "beverages",
    filterCategory: "chips",
    brand: "cocola",
  },
  {
    id: "pepsi",
    name: "Pepsi Can",
    subtitle: "330ml, Price",
    price: 4.99,
    image: require("./assets/pepsi.png"),
    section: "beverages",
    category: "beverages",
    filterCategory: "chips",
    brand: "cocola",
  },
  {
    id: "egg-red",
    name: "Egg Chicken Red",
    subtitle: "4pcs, Price",
    price: 1.99,
    image: require("./assets/egg.png"),
    section: "search",
    category: "dairy",
    filterCategory: "eggs",
    brand: "kazi-farmas",
  },
  {
    id: "egg-white",
    name: "Egg Chicken White",
    subtitle: "180g, Price",
    price: 1.5,
    image: require("./assets/egg2.png"),
    section: "search",
    category: "dairy",
    filterCategory: "eggs",
    brand: "kazi-farmas",
  },
  {
    id: "egg-pasta",
    name: "Egg Pasta",
    subtitle: "30gm, Price",
    price: 15.99,
    image: require("./assets/eggpasta.png"),
    section: "search",
    category: "bakery",
    filterCategory: "noodles",
    brand: "ifad",
  },
  {
    id: "egg-noodles",
    name: "Egg Noodles",
    subtitle: "2L, Price",
    price: 15.99,
    image: require("./assets/eggnoodle.png"),
    section: "search",
    category: "bakery",
    filterCategory: "noodles",
    brand: "ifad",
  },
  {
    id: "mayo-eggless",
    name: "Mayonnaise Eggless",
    subtitle: "325ml, Price",
    price: 4.99,
    image: require("./assets/mayonais.png"),
    section: "search",
    category: "dairy",
    filterCategory: "fast-food",
    brand: "individual-collection",
  },
  {
    id: "egg-noodles-2",
    name: "Egg Noodles",
    subtitle: "2L, Price",
    price: 15.99,
    image: require("./assets/eggnd.png"),
    section: "search",
    category: "bakery",
    filterCategory: "noodles",
    brand: "ifad",
  },
];

export const featuredProducts = products.filter((item) => item.section === "featured");
export const bestSellingProducts = products.filter((item) => item.section === "bestSelling");
export const groceryProducts = products.filter((item) => item.section === "groceries");
export const beveragesProducts = products.filter((item) => item.section === "beverages");
export const searchableProducts = products.filter(
  (item) => item.section === "search" || item.section === "beverages"
);

export const groceryHighlights = [
  {
    id: "pulses",
    name: "Pulses",
    tint: "#FDF1E3",
    image: require("./assets/pulses.png"),
  },
  {
    id: "rice",
    name: "Rice",
    tint: "#E9F7EE",
    image: require("./assets/rice.png"),
  },
];

export const defaultFavouriteIds = ["sprite", "diet-coke", "apple-grape", "coca", "pepsi"];

export const getProductById = (id) => products.find((item) => item.id === id);
export const formatPrice = (price) => `$${price.toFixed(2)}`;
